### ISSUE TITLE
Create Product Error

### ISSUE THREAD

**Issue by roblox-afk** [Redon-Tech/Roblox-Purchasing-Hub#14]
Error when creating product

Task exception was never retrieved
future: <Task finished name='nextcord: on_command_error' coro=<Client._run_event() done, defined at C:\Python310\lib\site-packages\nextcord\client.py:413> exception=HTTPException('400 Bad Request (error code: 50035): Invalid Form Body\nIn embeds.0.fields.3.value: This field is required')>
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\nextcord\client.py", line 420, in _run_event
    await self.on_error(event_name, *args, **kwargs)
  File "C:\Python310\lib\site-packages\nextcord\client.py", line 415, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Name\Desktop\WoodMartHub\Hub\BOT\lib\bot\__init__.py", line 125, in on_command_error
    raise exc.original
  File "C:\Python310\lib\site-packages\nextcord\ext\commands\core.py", line 168, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Name\Desktop\WoodMartHub\Hub\BOT\lib\cogs\product.py", line 661, in createproduct
    finalmessage = await ctx.send(embed=embed)
  File "C:\Python310\lib\site-packages\nextcord\abc.py", line 1422, in send
    data = await state.http.send_message(
  File "C:\Python310\lib\site-packages\nextcord\http.py", line 337, in request
    raise HTTPException(response, data)
nextcord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.0.fields.3.value: This field is required

**Comment by parker02311** [comment]
This is a more common occurring issue you need to make sure you spell "done" correctly and don't add anything but attachments otherwise this error occurs. It is a known bug to be patched in the next release.
